# Generated by Django 4.1.5 on 2023-02-02 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detalleIncentivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('idCiudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ciudadano')),
                ('idRecoleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recoleccion')),
                ('idTipoIncentivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tipoincentivo')),
            ],
        ),
    ]
