# Generated by Django 4.1.6 on 2023-02-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_nombre_tipodocumento_nombres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoincentivo',
            name='nombre',
            field=models.CharField(max_length=35),
        ),
    ]
