# Generated by Django 4.1.6 on 2023-02-06 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_ruta_ruta_nombreruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquinaria',
            name='nombre',
        ),
    ]
