# Generated by Django 4.1.6 on 2023-02-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_maquinaria_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaria',
            name='nombre',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
