# Generated by Django 4.1.6 on 2023-02-08 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_recoleccion_observacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoRecoleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='recoleccion',
            name='TipoRecoleccion_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tiporecoleccion'),
        ),
    ]
