# Generated by Django 4.1.6 on 2023-02-08 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_tiporecoleccion_recoleccion_tiporecoleccion_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tipoUsuario',
        ),
    ]
