# Generated by Django 4.1.5 on 2023-02-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_tipousuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciudadano',
            name='idEmpadro',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='idEmpadro',
        ),
        migrations.AlterField(
            model_name='personal',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='empadronamiento',
        ),
    ]
