# Generated by Django 4.1.6 on 2023-02-13 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_ciudadano_idempadro_remove_personal_idempadro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruta',
            old_name='nombreruta',
            new_name='nombre',
        ),
    ]
