# Generated by Django 4.1.6 on 2023-02-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_nombreruta_ruta_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumento',
            name='nombres',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
