# Generated by Django 4.1.5 on 2023-02-18 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_tipodocumento_nombres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipodocumento',
            old_name='nombres',
            new_name='nombre',
        ),
    ]
