# Generated by Django 4.1.6 on 2023-02-20 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_nombres_tipodocumento_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='medidaRecoleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='recoleccion',
            name='peso',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='recoleccion',
            name='medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.medidarecoleccion'),
        ),
    ]
